### ISSUE TITLE
Wt internal error when loading MNRL file

### ISSUE THREAD

**Issue by jackwadden** [dankramp/ANMLViewer#13]
![automata_lab_error](https://user-images.githubusercontent.com/847204/31182060-dfe9761a-a8f0-11e7-8ebe-c9ae0ced5b89.png)

I get this error message when attempting to open the following MRNL file: 
http://www.cs.virginia.edu/~jpw8bd/MISC/regex_n_100_c1.txt.mnrl

**Comment by dankramp** [comment]
Fixed with latest commit. Error was due to parsing a JSON object with a stray quotation mark in the symbol set. Solution was to escape quotation marks that appear in symbol set before parsing as JSON.
