### ISSUE TITLE
No way to undo "solo children" 

### ISSUE THREAD

**Issue by jackwadden** [dankramp/ANMLViewer#6]
If an element is right clicked and "solo-children" is selected, there is no way to get the rest of the automata back without running "show all nodes".

**Comment by jackwadden** [comment]
You actually can back out of this selection by right clicking on the pane and selecting "Show All Nodes". But would be nice if you could easily show/hide this selection.

**Comment by dankramp** [comment]
To explain why this may be difficult and likely not worth doing (but not impossible):

Node visibility is determined by a field called `hidden` for each node. If `hidden == true`, the node is not rendered. When a node's children are solo'ed, all nodes that are not children have their `hidden` property set to `true`. To unsolo children (implying returning to previous visibility state) would require saving data on each node's previous visibility state to return to. For efficiency reasons, it makes more sense just to have the user display all nodes again from the stage.
