### ISSUE TITLE
Print node data doesn't seem to do anything

### ISSUE THREAD

**Issue by jackwadden** [dankramp/ANMLViewer#7]
Right clicking on an STE and selecting "-Print Node Data-" doesn't seem to do anything.

**Comment by dankramp** [comment]
The data of the node is printed to the browser's console. Press F12 or open your browser's debugger to see the data.

**Comment by jackwadden** [comment]
Understood. Thanks!
Maybe something more descriptive like "Print To Debug Console" or something? As long as that's documented in the wiki or whitepaper it's fine as is. Just a suggestion.

**Comment by dankramp** [comment]
Documented [here](https://github.com/dankramp/AutomataLab/wiki/Editor-Mode#on-screen-functionality).
